### ISSUE TITLE
No Licence

### ISSUE THREAD

**Issue by macro32** [edgeware/python-circuit#6]
The project does not have a licence. Is this intentional? It looks like Copyright Law applies, which means it is not clear to what extent the code can be used or modified.

**Comment by avtobiff** [comment]
All source files have an Apache 2.0 license header (well, except
setup.py...)

    $ licensecheck -r *
    circuit/_twisted.py: Apache (v2.0)
    circuit/breaker.py: Apache (v2.0)
    circuit/__init__.py: Apache (v2.0)
    circuit/test/test_breaker.py: Apache (v2.0)
    circuit/test/test_twisted.py: Apache (v2.0)
    setup.py: *No copyright* UNKNOWN

This means that the project is licensed under the terms of the Apache
License 2.0.

I'll commit a full license text to clarify.

Thanks for your eye for detail!


As a sidenote, copyright law always apply; though, with free software
the copyright holder has decided to grant the user additional freedoms
(use, study, improve, and share) that All Rights Reserved does not
grant.

**Comment by macro32** [comment]
Thanks for the speedy response!
